version: '3.8'
services:
  web:
    build:
      context: ./src/
      dockerfile: Dockerfile
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 120
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - static_volume:/home/app/web/staticfiles/
      - media_volume:/home/app/web/mediafiles
  nginx:
    build: ./nginx/
    volumes:
      - static_volume:/home/app/web/staticfiles/
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  static_volume:
  media_volume:
